[package]
name = "word2vec-api"
version = "0.1.0"
authors = ["jayay <meine-adresse@live.de>"]
edition = "2018"

[dependencies]
word2vec = "0.3.1"
rocket = "0.4.2"


[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]
